services:
  quokkapack.api:
    build:
      context: .
      dockerfile: src/QuokkaPack.API/Dockerfile
    ports:
      - "7100:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

  quokkapack.razor:
    build:
      context: .
      dockerfile: src/QuokkaPack.Razor/Dockerfile
    ports:
      - "7200:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - DownstreamApi__BaseUrl=http://quokkapack.api
