// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuokkaPack.Data;

#nullable disable

namespace QuokkaPack.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("QuokkaPack.Data.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MasterUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MasterUserId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("QuokkaPack.Shared.Models.MasterUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MasterUsers");
                });

            modelBuilder.Entity("QuokkaPack.Shared.Models.UserLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MasterUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MasterUserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("QuokkaPack.Data.Models.Trip", b =>
                {
                    b.HasOne("QuokkaPack.Shared.Models.MasterUser", "MasterUser")
                        .WithMany("Trips")
                        .HasForeignKey("MasterUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterUser");
                });

            modelBuilder.Entity("QuokkaPack.Shared.Models.UserLogin", b =>
                {
                    b.HasOne("QuokkaPack.Shared.Models.MasterUser", "MasterUser")
                        .WithMany("Logins")
                        .HasForeignKey("MasterUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterUser");
                });

            modelBuilder.Entity("QuokkaPack.Shared.Models.MasterUser", b =>
                {
                    b.Navigation("Logins");

                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
