// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuokkaPack.Data;

#nullable disable

namespace QuokkaPack.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250707232841_AddItemsToTrip")]
    partial class AddItemsToTrip
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("CategoryItem", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoriesId", "ItemsId");

                    b.HasIndex("ItemsId");

                    b.ToTable("CategoryItem");
                });

            modelBuilder.Entity("CategoryTrip", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TripsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoriesId", "TripsId");

                    b.HasIndex("TripsId");

                    b.ToTable("CategoryTrip");
                });

            modelBuilder.Entity("QuokkaPack.Data.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MasterUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MasterUserId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("QuokkaPack.Shared.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MasterUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MasterUserId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("QuokkaPack.Shared.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEssential")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MasterUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TripId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MasterUserId");

                    b.HasIndex("TripId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("QuokkaPack.Shared.Models.MasterUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MasterUsers");
                });

            modelBuilder.Entity("QuokkaPack.Shared.Models.UserLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MasterUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MasterUserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("CategoryItem", b =>
                {
                    b.HasOne("QuokkaPack.Shared.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuokkaPack.Shared.Models.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CategoryTrip", b =>
                {
                    b.HasOne("QuokkaPack.Shared.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuokkaPack.Data.Models.Trip", null)
                        .WithMany()
                        .HasForeignKey("TripsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuokkaPack.Data.Models.Trip", b =>
                {
                    b.HasOne("QuokkaPack.Shared.Models.MasterUser", "MasterUser")
                        .WithMany("Trips")
                        .HasForeignKey("MasterUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterUser");
                });

            modelBuilder.Entity("QuokkaPack.Shared.Models.Category", b =>
                {
                    b.HasOne("QuokkaPack.Shared.Models.MasterUser", "MasterUser")
                        .WithMany()
                        .HasForeignKey("MasterUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterUser");
                });

            modelBuilder.Entity("QuokkaPack.Shared.Models.Item", b =>
                {
                    b.HasOne("QuokkaPack.Shared.Models.MasterUser", "MasterUser")
                        .WithMany()
                        .HasForeignKey("MasterUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuokkaPack.Data.Models.Trip", null)
                        .WithMany("Item")
                        .HasForeignKey("TripId");

                    b.Navigation("MasterUser");
                });

            modelBuilder.Entity("QuokkaPack.Shared.Models.UserLogin", b =>
                {
                    b.HasOne("QuokkaPack.Shared.Models.MasterUser", "MasterUser")
                        .WithMany("Logins")
                        .HasForeignKey("MasterUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterUser");
                });

            modelBuilder.Entity("QuokkaPack.Data.Models.Trip", b =>
                {
                    b.Navigation("Item");
                });

            modelBuilder.Entity("QuokkaPack.Shared.Models.MasterUser", b =>
                {
                    b.Navigation("Logins");

                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
