// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuokkaPack.Data;

#nullable disable

namespace QuokkaPack.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251007173846_PendingChanges")]
    partial class PendingChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("QuokkaPack.Shared.Models.AppUserLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MasterUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MasterUserId");

                    b.ToTable("AppUserLogins");
                });

            modelBuilder.Entity("QuokkaPack.Shared.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<Guid>("MasterUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MasterUserId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDefault = false,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Toiletries"
                        },
                        new
                        {
                            Id = 2,
                            IsDefault = false,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            IsDefault = false,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 4,
                            IsDefault = false,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Outdoor Gear"
                        },
                        new
                        {
                            Id = 5,
                            IsDefault = false,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Snacks"
                        },
                        new
                        {
                            Id = 6,
                            IsDefault = false,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Documents"
                        });
                });

            modelBuilder.Entity("QuokkaPack.Shared.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<Guid>("MasterUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("MasterUserId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Toothbrush"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Toothpaste"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Shampoo"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Deodorant"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Razor"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Face Wash"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Floss"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "T-shirts"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Jeans"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Sweater"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Raincoat"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Socks"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Underwear"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Pajamas"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Hat"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Phone Charger"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Power Bank"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Headphones"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 3,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 3,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Kindle"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "USB Cable"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 4,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Hiking Boots"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 4,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Tent"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 4,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Sleeping Bag"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 4,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Flashlight"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 4,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Water Bottle"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 4,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Backpack"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 5,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Granola Bars"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 5,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Trail Mix"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 5,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Jerky"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 5,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Fruit Snacks"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 5,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Protein Bars"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 6,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Passport"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 6,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Boarding Pass"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 6,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Travel Insurance"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 6,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Itinerary"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 6,
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "ID Card"
                        });
                });

            modelBuilder.Entity("QuokkaPack.Shared.Models.MasterUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MasterUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("QuokkaPack.Shared.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("MasterUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("MasterUserId");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Destination = "Tokyo",
                            EndDate = new DateOnly(2025, 4, 24),
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            StartDate = new DateOnly(2025, 4, 10)
                        },
                        new
                        {
                            Id = 2,
                            Destination = "Yosemite",
                            EndDate = new DateOnly(2025, 6, 8),
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            StartDate = new DateOnly(2025, 6, 1)
                        },
                        new
                        {
                            Id = 3,
                            Destination = "Paris",
                            EndDate = new DateOnly(2025, 7, 30),
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            StartDate = new DateOnly(2025, 7, 15)
                        },
                        new
                        {
                            Id = 4,
                            Destination = "Banff",
                            EndDate = new DateOnly(2025, 9, 20),
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            StartDate = new DateOnly(2025, 9, 10)
                        },
                        new
                        {
                            Id = 5,
                            Destination = "New York City",
                            EndDate = new DateOnly(2025, 12, 27),
                            MasterUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            StartDate = new DateOnly(2025, 12, 20)
                        });
                });

            modelBuilder.Entity("QuokkaPack.Shared.Models.TripItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPacked")
                        .HasColumnType("bit");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("TripId");

                    b.ToTable("TripItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsPacked = false,
                            ItemId = 8,
                            TripId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsPacked = true,
                            ItemId = 9,
                            TripId = 1
                        },
                        new
                        {
                            Id = 3,
                            IsPacked = false,
                            ItemId = 10,
                            TripId = 1
                        },
                        new
                        {
                            Id = 4,
                            IsPacked = true,
                            ItemId = 11,
                            TripId = 1
                        },
                        new
                        {
                            Id = 5,
                            IsPacked = false,
                            ItemId = 12,
                            TripId = 1
                        },
                        new
                        {
                            Id = 6,
                            IsPacked = true,
                            ItemId = 13,
                            TripId = 1
                        },
                        new
                        {
                            Id = 7,
                            IsPacked = false,
                            ItemId = 14,
                            TripId = 1
                        },
                        new
                        {
                            Id = 8,
                            IsPacked = true,
                            ItemId = 15,
                            TripId = 1
                        },
                        new
                        {
                            Id = 9,
                            IsPacked = false,
                            ItemId = 16,
                            TripId = 1
                        },
                        new
                        {
                            Id = 10,
                            IsPacked = true,
                            ItemId = 17,
                            TripId = 1
                        },
                        new
                        {
                            Id = 11,
                            IsPacked = false,
                            ItemId = 18,
                            TripId = 1
                        },
                        new
                        {
                            Id = 12,
                            IsPacked = true,
                            ItemId = 19,
                            TripId = 1
                        },
                        new
                        {
                            Id = 13,
                            IsPacked = false,
                            ItemId = 20,
                            TripId = 1
                        },
                        new
                        {
                            Id = 14,
                            IsPacked = true,
                            ItemId = 21,
                            TripId = 1
                        },
                        new
                        {
                            Id = 15,
                            IsPacked = false,
                            ItemId = 22,
                            TripId = 1
                        },
                        new
                        {
                            Id = 16,
                            IsPacked = true,
                            ItemId = 23,
                            TripId = 1
                        },
                        new
                        {
                            Id = 17,
                            IsPacked = false,
                            ItemId = 24,
                            TripId = 1
                        },
                        new
                        {
                            Id = 18,
                            IsPacked = true,
                            ItemId = 25,
                            TripId = 1
                        },
                        new
                        {
                            Id = 19,
                            IsPacked = false,
                            ItemId = 26,
                            TripId = 1
                        },
                        new
                        {
                            Id = 20,
                            IsPacked = true,
                            ItemId = 27,
                            TripId = 1
                        },
                        new
                        {
                            Id = 21,
                            IsPacked = false,
                            ItemId = 28,
                            TripId = 1
                        },
                        new
                        {
                            Id = 22,
                            IsPacked = true,
                            ItemId = 29,
                            TripId = 1
                        },
                        new
                        {
                            Id = 23,
                            IsPacked = false,
                            ItemId = 30,
                            TripId = 1
                        },
                        new
                        {
                            Id = 24,
                            IsPacked = true,
                            ItemId = 31,
                            TripId = 1
                        },
                        new
                        {
                            Id = 25,
                            IsPacked = false,
                            ItemId = 32,
                            TripId = 1
                        },
                        new
                        {
                            Id = 26,
                            IsPacked = false,
                            ItemId = 1,
                            TripId = 2
                        },
                        new
                        {
                            Id = 27,
                            IsPacked = true,
                            ItemId = 2,
                            TripId = 2
                        },
                        new
                        {
                            Id = 28,
                            IsPacked = false,
                            ItemId = 3,
                            TripId = 2
                        },
                        new
                        {
                            Id = 29,
                            IsPacked = true,
                            ItemId = 4,
                            TripId = 2
                        },
                        new
                        {
                            Id = 30,
                            IsPacked = false,
                            ItemId = 5,
                            TripId = 2
                        },
                        new
                        {
                            Id = 31,
                            IsPacked = true,
                            ItemId = 6,
                            TripId = 2
                        },
                        new
                        {
                            Id = 32,
                            IsPacked = false,
                            ItemId = 7,
                            TripId = 2
                        },
                        new
                        {
                            Id = 33,
                            IsPacked = true,
                            ItemId = 8,
                            TripId = 2
                        },
                        new
                        {
                            Id = 34,
                            IsPacked = false,
                            ItemId = 9,
                            TripId = 2
                        },
                        new
                        {
                            Id = 35,
                            IsPacked = true,
                            ItemId = 10,
                            TripId = 2
                        },
                        new
                        {
                            Id = 36,
                            IsPacked = false,
                            ItemId = 11,
                            TripId = 2
                        },
                        new
                        {
                            Id = 37,
                            IsPacked = true,
                            ItemId = 12,
                            TripId = 2
                        },
                        new
                        {
                            Id = 38,
                            IsPacked = false,
                            ItemId = 13,
                            TripId = 2
                        },
                        new
                        {
                            Id = 39,
                            IsPacked = true,
                            ItemId = 14,
                            TripId = 2
                        },
                        new
                        {
                            Id = 40,
                            IsPacked = false,
                            ItemId = 15,
                            TripId = 2
                        },
                        new
                        {
                            Id = 41,
                            IsPacked = true,
                            ItemId = 16,
                            TripId = 2
                        },
                        new
                        {
                            Id = 42,
                            IsPacked = false,
                            ItemId = 17,
                            TripId = 2
                        },
                        new
                        {
                            Id = 43,
                            IsPacked = true,
                            ItemId = 18,
                            TripId = 2
                        },
                        new
                        {
                            Id = 44,
                            IsPacked = false,
                            ItemId = 19,
                            TripId = 2
                        },
                        new
                        {
                            Id = 45,
                            IsPacked = true,
                            ItemId = 20,
                            TripId = 2
                        },
                        new
                        {
                            Id = 46,
                            IsPacked = false,
                            ItemId = 21,
                            TripId = 2
                        },
                        new
                        {
                            Id = 47,
                            IsPacked = true,
                            ItemId = 22,
                            TripId = 2
                        },
                        new
                        {
                            Id = 48,
                            IsPacked = false,
                            ItemId = 23,
                            TripId = 2
                        },
                        new
                        {
                            Id = 49,
                            IsPacked = true,
                            ItemId = 24,
                            TripId = 2
                        },
                        new
                        {
                            Id = 50,
                            IsPacked = false,
                            ItemId = 25,
                            TripId = 2
                        },
                        new
                        {
                            Id = 51,
                            IsPacked = true,
                            ItemId = 26,
                            TripId = 2
                        },
                        new
                        {
                            Id = 52,
                            IsPacked = false,
                            ItemId = 27,
                            TripId = 2
                        },
                        new
                        {
                            Id = 53,
                            IsPacked = true,
                            ItemId = 28,
                            TripId = 2
                        },
                        new
                        {
                            Id = 54,
                            IsPacked = false,
                            ItemId = 29,
                            TripId = 2
                        },
                        new
                        {
                            Id = 55,
                            IsPacked = true,
                            ItemId = 30,
                            TripId = 2
                        },
                        new
                        {
                            Id = 56,
                            IsPacked = false,
                            ItemId = 31,
                            TripId = 2
                        },
                        new
                        {
                            Id = 57,
                            IsPacked = true,
                            ItemId = 32,
                            TripId = 2
                        },
                        new
                        {
                            Id = 58,
                            IsPacked = false,
                            ItemId = 8,
                            TripId = 3
                        },
                        new
                        {
                            Id = 59,
                            IsPacked = true,
                            ItemId = 9,
                            TripId = 3
                        },
                        new
                        {
                            Id = 60,
                            IsPacked = false,
                            ItemId = 10,
                            TripId = 3
                        },
                        new
                        {
                            Id = 61,
                            IsPacked = true,
                            ItemId = 11,
                            TripId = 3
                        },
                        new
                        {
                            Id = 62,
                            IsPacked = false,
                            ItemId = 12,
                            TripId = 3
                        },
                        new
                        {
                            Id = 63,
                            IsPacked = true,
                            ItemId = 13,
                            TripId = 3
                        },
                        new
                        {
                            Id = 64,
                            IsPacked = false,
                            ItemId = 14,
                            TripId = 3
                        },
                        new
                        {
                            Id = 65,
                            IsPacked = true,
                            ItemId = 15,
                            TripId = 3
                        },
                        new
                        {
                            Id = 66,
                            IsPacked = false,
                            ItemId = 16,
                            TripId = 3
                        },
                        new
                        {
                            Id = 67,
                            IsPacked = true,
                            ItemId = 17,
                            TripId = 3
                        },
                        new
                        {
                            Id = 68,
                            IsPacked = false,
                            ItemId = 18,
                            TripId = 3
                        },
                        new
                        {
                            Id = 69,
                            IsPacked = true,
                            ItemId = 19,
                            TripId = 3
                        },
                        new
                        {
                            Id = 70,
                            IsPacked = false,
                            ItemId = 20,
                            TripId = 3
                        },
                        new
                        {
                            Id = 71,
                            IsPacked = true,
                            ItemId = 21,
                            TripId = 3
                        },
                        new
                        {
                            Id = 72,
                            IsPacked = false,
                            ItemId = 22,
                            TripId = 3
                        },
                        new
                        {
                            Id = 73,
                            IsPacked = true,
                            ItemId = 23,
                            TripId = 3
                        },
                        new
                        {
                            Id = 74,
                            IsPacked = false,
                            ItemId = 24,
                            TripId = 3
                        },
                        new
                        {
                            Id = 75,
                            IsPacked = true,
                            ItemId = 25,
                            TripId = 3
                        },
                        new
                        {
                            Id = 76,
                            IsPacked = false,
                            ItemId = 26,
                            TripId = 3
                        },
                        new
                        {
                            Id = 77,
                            IsPacked = true,
                            ItemId = 27,
                            TripId = 3
                        },
                        new
                        {
                            Id = 78,
                            IsPacked = false,
                            ItemId = 1,
                            TripId = 4
                        },
                        new
                        {
                            Id = 79,
                            IsPacked = true,
                            ItemId = 2,
                            TripId = 4
                        },
                        new
                        {
                            Id = 80,
                            IsPacked = false,
                            ItemId = 3,
                            TripId = 4
                        },
                        new
                        {
                            Id = 81,
                            IsPacked = true,
                            ItemId = 4,
                            TripId = 4
                        },
                        new
                        {
                            Id = 82,
                            IsPacked = false,
                            ItemId = 5,
                            TripId = 4
                        },
                        new
                        {
                            Id = 83,
                            IsPacked = true,
                            ItemId = 6,
                            TripId = 4
                        },
                        new
                        {
                            Id = 84,
                            IsPacked = false,
                            ItemId = 7,
                            TripId = 4
                        },
                        new
                        {
                            Id = 85,
                            IsPacked = true,
                            ItemId = 8,
                            TripId = 4
                        },
                        new
                        {
                            Id = 86,
                            IsPacked = false,
                            ItemId = 9,
                            TripId = 4
                        },
                        new
                        {
                            Id = 87,
                            IsPacked = true,
                            ItemId = 10,
                            TripId = 4
                        },
                        new
                        {
                            Id = 88,
                            IsPacked = false,
                            ItemId = 11,
                            TripId = 4
                        },
                        new
                        {
                            Id = 89,
                            IsPacked = true,
                            ItemId = 12,
                            TripId = 4
                        },
                        new
                        {
                            Id = 90,
                            IsPacked = false,
                            ItemId = 13,
                            TripId = 4
                        },
                        new
                        {
                            Id = 91,
                            IsPacked = true,
                            ItemId = 14,
                            TripId = 4
                        },
                        new
                        {
                            Id = 92,
                            IsPacked = false,
                            ItemId = 15,
                            TripId = 4
                        },
                        new
                        {
                            Id = 93,
                            IsPacked = true,
                            ItemId = 16,
                            TripId = 4
                        },
                        new
                        {
                            Id = 94,
                            IsPacked = false,
                            ItemId = 17,
                            TripId = 4
                        },
                        new
                        {
                            Id = 95,
                            IsPacked = true,
                            ItemId = 18,
                            TripId = 4
                        },
                        new
                        {
                            Id = 96,
                            IsPacked = false,
                            ItemId = 19,
                            TripId = 4
                        },
                        new
                        {
                            Id = 97,
                            IsPacked = true,
                            ItemId = 20,
                            TripId = 4
                        },
                        new
                        {
                            Id = 98,
                            IsPacked = false,
                            ItemId = 21,
                            TripId = 4
                        },
                        new
                        {
                            Id = 99,
                            IsPacked = true,
                            ItemId = 22,
                            TripId = 4
                        },
                        new
                        {
                            Id = 100,
                            IsPacked = false,
                            ItemId = 23,
                            TripId = 4
                        },
                        new
                        {
                            Id = 101,
                            IsPacked = true,
                            ItemId = 24,
                            TripId = 4
                        },
                        new
                        {
                            Id = 102,
                            IsPacked = false,
                            ItemId = 25,
                            TripId = 4
                        },
                        new
                        {
                            Id = 103,
                            IsPacked = true,
                            ItemId = 26,
                            TripId = 4
                        },
                        new
                        {
                            Id = 104,
                            IsPacked = false,
                            ItemId = 27,
                            TripId = 4
                        },
                        new
                        {
                            Id = 105,
                            IsPacked = false,
                            ItemId = 8,
                            TripId = 5
                        },
                        new
                        {
                            Id = 106,
                            IsPacked = true,
                            ItemId = 9,
                            TripId = 5
                        },
                        new
                        {
                            Id = 107,
                            IsPacked = false,
                            ItemId = 10,
                            TripId = 5
                        },
                        new
                        {
                            Id = 108,
                            IsPacked = true,
                            ItemId = 11,
                            TripId = 5
                        },
                        new
                        {
                            Id = 109,
                            IsPacked = false,
                            ItemId = 12,
                            TripId = 5
                        },
                        new
                        {
                            Id = 110,
                            IsPacked = true,
                            ItemId = 13,
                            TripId = 5
                        },
                        new
                        {
                            Id = 111,
                            IsPacked = false,
                            ItemId = 14,
                            TripId = 5
                        },
                        new
                        {
                            Id = 112,
                            IsPacked = true,
                            ItemId = 15,
                            TripId = 5
                        },
                        new
                        {
                            Id = 113,
                            IsPacked = false,
                            ItemId = 16,
                            TripId = 5
                        },
                        new
                        {
                            Id = 114,
                            IsPacked = true,
                            ItemId = 17,
                            TripId = 5
                        },
                        new
                        {
                            Id = 115,
                            IsPacked = false,
                            ItemId = 18,
                            TripId = 5
                        },
                        new
                        {
                            Id = 116,
                            IsPacked = true,
                            ItemId = 19,
                            TripId = 5
                        },
                        new
                        {
                            Id = 117,
                            IsPacked = false,
                            ItemId = 20,
                            TripId = 5
                        },
                        new
                        {
                            Id = 118,
                            IsPacked = true,
                            ItemId = 21,
                            TripId = 5
                        },
                        new
                        {
                            Id = 119,
                            IsPacked = false,
                            ItemId = 22,
                            TripId = 5
                        },
                        new
                        {
                            Id = 120,
                            IsPacked = true,
                            ItemId = 23,
                            TripId = 5
                        },
                        new
                        {
                            Id = 121,
                            IsPacked = false,
                            ItemId = 24,
                            TripId = 5
                        },
                        new
                        {
                            Id = 122,
                            IsPacked = true,
                            ItemId = 25,
                            TripId = 5
                        },
                        new
                        {
                            Id = 123,
                            IsPacked = false,
                            ItemId = 26,
                            TripId = 5
                        },
                        new
                        {
                            Id = 124,
                            IsPacked = true,
                            ItemId = 27,
                            TripId = 5
                        },
                        new
                        {
                            Id = 125,
                            IsPacked = false,
                            ItemId = 28,
                            TripId = 5
                        },
                        new
                        {
                            Id = 126,
                            IsPacked = true,
                            ItemId = 29,
                            TripId = 5
                        },
                        new
                        {
                            Id = 127,
                            IsPacked = false,
                            ItemId = 30,
                            TripId = 5
                        },
                        new
                        {
                            Id = 128,
                            IsPacked = true,
                            ItemId = 31,
                            TripId = 5
                        },
                        new
                        {
                            Id = 129,
                            IsPacked = false,
                            ItemId = 32,
                            TripId = 5
                        },
                        new
                        {
                            Id = 130,
                            IsPacked = true,
                            ItemId = 33,
                            TripId = 5
                        },
                        new
                        {
                            Id = 131,
                            IsPacked = false,
                            ItemId = 34,
                            TripId = 5
                        },
                        new
                        {
                            Id = 132,
                            IsPacked = true,
                            ItemId = 35,
                            TripId = 5
                        },
                        new
                        {
                            Id = 133,
                            IsPacked = false,
                            ItemId = 36,
                            TripId = 5
                        },
                        new
                        {
                            Id = 134,
                            IsPacked = true,
                            ItemId = 37,
                            TripId = 5
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuokkaPack.Shared.Models.AppUserLogin", b =>
                {
                    b.HasOne("QuokkaPack.Shared.Models.MasterUser", "MasterUser")
                        .WithMany("Logins")
                        .HasForeignKey("MasterUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterUser");
                });

            modelBuilder.Entity("QuokkaPack.Shared.Models.Category", b =>
                {
                    b.HasOne("QuokkaPack.Shared.Models.MasterUser", "MasterUser")
                        .WithMany("Categories")
                        .HasForeignKey("MasterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MasterUser");
                });

            modelBuilder.Entity("QuokkaPack.Shared.Models.Item", b =>
                {
                    b.HasOne("QuokkaPack.Shared.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuokkaPack.Shared.Models.MasterUser", "MasterUser")
                        .WithMany("Items")
                        .HasForeignKey("MasterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("MasterUser");
                });

            modelBuilder.Entity("QuokkaPack.Shared.Models.Trip", b =>
                {
                    b.HasOne("QuokkaPack.Shared.Models.MasterUser", "MasterUser")
                        .WithMany("Trips")
                        .HasForeignKey("MasterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MasterUser");
                });

            modelBuilder.Entity("QuokkaPack.Shared.Models.TripItem", b =>
                {
                    b.HasOne("QuokkaPack.Shared.Models.Item", "Item")
                        .WithMany("TripItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuokkaPack.Shared.Models.Trip", "Trip")
                        .WithMany("TripItems")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("QuokkaPack.Shared.Models.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("QuokkaPack.Shared.Models.Item", b =>
                {
                    b.Navigation("TripItems");
                });

            modelBuilder.Entity("QuokkaPack.Shared.Models.MasterUser", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Items");

                    b.Navigation("Logins");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("QuokkaPack.Shared.Models.Trip", b =>
                {
                    b.Navigation("TripItems");
                });
#pragma warning restore 612, 618
        }
    }
}
