/**
 * Central type definitions for the Angular application.
 *
 * This file re-exports types from the auto-generated NSwag client (api-client.ts).
 * All DTOs are automatically kept in sync with the .NET API.
 *
 * Auto-generated by NSwag when API controllers/DTOs/models change.
 * Do not manually edit the types - they will be overwritten.
 *
 * You can add custom view models or type extensions here.
 */

// Re-export all DTO types from the NSwag-generated client
export {
  TripDetailsReadDto,
  TripSummaryReadDto,
  TripItemReadDto,
  ItemReadDto,
  CategoryReadDto,
  TripEditDto,
  TripItemCreateDto,
  TripItemEditDto,
  TripCreateDto,
  ItemCreateDto,
  ItemEditDto,
  CategoryCreateDto,
  CategoryEditDto,
} from '../../../app/api/api-client';

// Custom view models and type extensions can be added below
// Example:
// export type ItemVM = ItemReadDto & { isEditing?: boolean };
